#!/usr/bin/env ruby

require 'bundler/setup'

begin
  require File.expand_path('../../lib/parrot.rb', File.realpath(__FILE__))
  Parrot::Parrot.new(ARGV).run
rescue StandardError => e
  warn "Fatal error: #{e.message}"
  warn e.backtrace.join("\n")
  exit 1
end
